name: Bug report
description: File a bug report
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: E.g. "the `.env` method fails to upload to the Edge Addons store"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      placeholder:
        "E.g. have an `.env` file like so:" |
        "```env" |
        "EXT_ID=12345" |
        "..."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: Uploading to this store should be possible
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What's the version you're running?
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
