name: Feature request
description: Suggest a new idea for the tool
title: "[Feature request] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Describe the feature you're missing
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What method is it related to?
      options:
        - `.env` files
        - CLI API
        - Node.js API
        - Other
    validations:
      required: true
